name: Functional iOS App Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:


jobs:
    iOS-app:
      runs-on: macos-13
      steps:
        - name: â¬‡ï¸ Checkout Repository
          uses: actions/checkout@v3

        - name: ğŸŸ¢ Setup Node.js
          uses: actions/setup-node@v3
          with:
              node-version-file: '.nvmrc'

        - name: ğŸ§© Install Dependencies
          run: npm ci

        - name: ğŸ“¦ Download app
          run: |
              mkdir apps
              wget https://github.com/webdriverio/native-demo-app/releases/download/v1.0.8/ios.simulator.wdio.native.app.v1.0.8.zip -P apps

        # - name: â˜• Setup Java and Android SDK
        #   uses: actions/setup-java@v4
        #   with:
        #       java-version: '11'
        #       distribution: 'temurin'

        - name: ğŸ“± Create Simulator
          uses: futureware-tech/simulator-action@v3
          with:
            model: 'iPhone 14'
            os: 'iOS'
            os_version: '17.2'

        - name: ğŸ“² Run Tests on iOS Simulator
          run: npm run ios.app

        - name: ğŸ’¾ Save server output
          if: failure()
          uses: actions/upload-artifact@v4
          with:
              name: android-runner-output
              path: |
                  logs/
