name: Functional iOS App Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  ios-app:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout Repository
        uses: actions/checkout@v3

      - name: ğŸŸ¢ Setup Node.js
        uses: actions/setup-node@v3
        with:
            node-version-file: '.nvmrc'

      - name: ğŸ§© Install Dependencies
        run: |
          npm ci

      - name: ğŸ“¦ Download app
        run: |
            mkdir -p apps
            wget https://github.com/webdriverio/native-demo-app/releases/download/v1.0.8/ios.simulator.wdio.native.app.v1.0.8.zip -P apps

      - name: ğŸ“¬ Upload App to Sauce Labs
        run: |
            curl -v \
                -F "payload=@./apps/ios.simulator.wdio.native.app.v1.0.8.zip" \
                -F name=wdio-demo-app-ios.zip \
                -u "${{ secrets.SAUCE_USERNAME }}:${{ secrets.SAUCE_ACCESS_KEY }}" \
                'https://api.eu-central-1.saucelabs.com/v1/storage/upload'

      - name: ğŸ“² Run Tests on an iOS Simulator
        run: npm run ios.sauce.simulators.app.eu

    # Not needed now we are running on Sauce Labs
    #   - name: ğŸ’¾ Save server output
    #     if: failure()
    #     uses: actions/upload-artifact@v4
    #     with:
    #         name: iOS-runner-output
    #         path: |
    #             logs/
